#!/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2025 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝

source $SHELIXPATH/env/layouts.sh


# Store the functions in an array
functions=($(typeset -f | awk '/ \(\) $/ && !/^main / {print "\"" $1 "\""}'))

# Check if no param is passed as $1
if [ $# -eq 0 ]; then
    # Construct the JSON array manually
    json="["
    for func in "${functions[@]}"; do
        json+=" $func,"
    done
    json="${json%,}"
    json+=" ]"
    
    echo "$json"
else
    # Run (layout name) function
    "$@"
fi
