#!/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2024 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝

# source $SHELIXPATH/env/layouts.sh
source $SHELIXPATH/env/utils.sh

# Check if a parameter is provided
if [ $# -eq 0 ]; then
  # echo "$json"
  # echo '["base","vertical","nerd","minimal"]'
  echo $(ls $SHELIXPATH/libs/layouts) | jq -Rc 'split(" ")'
else
  # tmux confirm-before -p "Kill all pane on this window? (y/n)" "" &&
  tmux kill-pane -a 
  # Run (layout) function
  # "$@"
  "$SHELIXPATH"/libs/layouts/"$@" "$SHELIXSESSIONDIR"
  # renameEditorsPanes
fi
