#!/usr/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2024 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝

# Accordion template 
# Responsive layout
# Remove the hook as necessary
# Using the hook array[100] force overwriting any hooks that may have been set on this window

for i in {0..10}
do
  tmux split-window -t $i -h
  # sleep 0.08 
  # tmux send-keys -t $i "cd $SHELIXSESSIONDIR" Enter
done

# sleep 0.2 

for i in {1..10}
do
  tmux send-keys -t $i "hx" Enter
  tmux select-pane -t $i -T 'hx'
done


tmux select-pane -t 0 -T 'shelix'
tmux send-keys -t 0 "shelix" Enter


tmux resize-pane -t 0 -x 16%
tmux resize-pane -t 1 -x 82%


tmux set-hook pane-focus-out[101] "run 'on_focus -x 82% -n shelix'"
