#!/usr/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2024 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝

# cd ..

tmux split-window -h 
tmux split-window -t 1 -h
tmux split-window -t 2 -h
tmux split-window -t 2 -v 
tmux split-window -t 3 -v 
tmux split-window -t 4 -v 

# tmux resize-pane -t 0 -x 14%
tmux resize-pane -t 1 -x 20%
tmux resize-pane -t 2 -x 38%
tmux resize-pane -t 6 -x 35%


# cd_panes
# sleep 10
# notify "$(echo $SHELIXSESSIONDIR)"

# tmux send-keys -t 0 "cd $SHELIXSESSIONDIR" Enter

for i in {0..10}
do
  tmux send-keys -t $i "source $SHELIXPATH/env/shelix.conf.sh ; cd $SHELIXSESSIONDIR" Enter
done

# tmux send-keys -t 1 "cd $SHELIXSESSIONDIR" Enter
# tmux send-keys -t 2 "cd $SHELIXSESSIONDIR" Enter
# tmux send-keys -t 3 "cd $SHELIXSESSIONDIR" Enter
# tmux send-keys -t 4 "cd $SHELIXSESSIONDIR" Enter
# tmux send-keys -t 5 "cd $SHELIXSESSIONDIR" Enter
# tmux send-keys -t 6 "cd $SHELIXSESSIONDIR" Enter
sleep 0.1

tmux send-keys -t 0 "hx" Enter
tmux send-keys -t 1 "hx" Enter
tmux send-keys -t 3 "shelix" Enter
tmux send-keys -t 6 "hx" Enter


tmux selectp -t 1 -T "hx"
# tmux selectp -t 2 -T "$SHELL"
# tmux selectp -t 4 -T "$SHELL"
# tmux selectp -t 5 -T "$SHELL"
tmux selectp -t 6 -T "hx"

tmux kill-pane -t 0

# Taht remove all hooks globally
# tmux set-hook -g pane-focus-out[0] "run 'echo'"

tmux set-hook pane-focus-out[100] "run 'on_focus -x 100% -y 50%'"


