#!/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2024 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝

# List available panes, and catch focus on a pane at selection
#notify "$1"
# We use the same tool to list and trigger the action.
# If $1 is set, trigger
if [ -n "$1" ]; then
    #tmux display-popup -h 3 -w 33% -E "echo -e '\033[7;5;1m Send keys to session $1:\e[0m \c'; read send ; tmux send -t $1 \"\$send\" Enter ; rm /tmp/send.txt"
    #notify "$1"
    WINDOW=$(echo "$1" | cut -d ':' -f 1)
    tmux select-window -t $WINDOW
    # Close the popup, if it's one
    if [ -z "$TMUX_PANE" ]; then
      tmux display-popup -C
    fi
else
    # Convert multiline to JSON
    json=$(tmux list-windows | sed 's/.*/"&"/' | paste -sd, | sed 's/^/[/; s/$/]/')

    echo "$json"
    
fi


