#!/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2024 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝


# lfmux(){
#   local TEMP=$(mktemp)
#   tmux popup -h 90% -w 90% -E lf -selection-path=$TEMP
#   # cat $TEMP
#   editors=($(tmux list-panes -t 0 -F '#{pane_current_command}'))
#   for index in "${!editors[@]}"; do
#       if [ "${editors[$index]}" = "hx" ]; then
#           tmux send-keys -t ":.$index" Escape
#           tmux send-keys -t ":.$index" ":o $(cat $TEMP)" ENTER
#       fi
#   done

# }

# lfmux





# List of pane titles
running=($(tmux list-panes -F "#{pane_title}"))


if [ -n "$1" ];then
  FILE="${1}"
fi
  

# k if ran from inside a popup
if [ -z "$TMUX_PANE" ]; then
  tmux send-keys Escape
  yazi --chooser-file /tmp/yazi_selection.txt
  # Loop through all pane titles
  for index in "${!running[@]}"; do
      # Check if the title contains the string "hx"
    if [[ "${running[$index]}" == *"hx"* ]]; then
          tmux send-keys -t ":.$index" Escape
          tmux send-keys -t ":.$index" ":o $(cat /tmp/yazi_selection.txt)" Enter
     fi
  done
  # tmux send-keys ":o $FILE" ENTER
  exit
else
  yazi_embed
fi
