#!/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2024 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝

# Open new shell

MARKED=$(tmux display -p -t '~' '#D')

# Check if ran from inside a popup
# Allow to target the current pane directly
# In this case the program will exit early
if [ -z "$TMUX_PANE" ]; then
  if [ -n "$MARKED" ]; then
     tmux split-window -t '~' -vb
     #exit
  else
      tmux split-window -vb
      tmux popup -C
  fi
  #exit
fi

# If a pane is marked we split that one
if [ -z "$MARKED" ]; then
  notify 'No pane were marked.' 0.5
  tmux split-window -vb
else
  # Split marked pane
  tmux split-window -t '~' -vb
fi


