#!/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2025 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝

NETCARD="$(cat $SHELIXPATH/env/.conf.json | jq --raw-output .hardware.netcard)"

# Debugging
# echo $NETCARD
# exit
# NETCARD="wlx00c0ca82d1f2" # Pass in your network card (see ifconfig or ip route)
# echo $NETCARD
# exit

awk '{if(l1){printf "%.2fKB/s ⇵ %.2fKB/s\n", ($2-l1)/1024, ($10-l2)/1024} else{l1=$2; l2=$10;}}' \
    <(grep "$NETCARD" /proc/net/dev) <(sleep 2; grep "$NETCARD" /proc/net/dev)
