#!/bin/bash
# ╔-----------------------------------------------------------------------╗
# ║                                                                       ║
# ║ This file is part of the Shelix IDE.                                  ║
# ║ Copyright (C) 2024 NVRM webdev23 https://github.com/webdev23          ║
# ║                                                                       ║
# ║ This program is free software: you can redistribute it and/or modify  ║
# ║ it under the terms of the GNU General Public License as published by  ║
# ║ the Free Software Foundation, either version 3 of the License, or     ║
# ║ (at your option) any later version.                                   ║
# ║                                                                       ║
# ║ This program is distributed in the hope that it will be useful,       ║
# ║ but WITHOUT ANY WARRANTY; without even the implied warranty of        ║
# ║ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ║
# ║ GNU General Public License for more details.                          ║
# ║                                                                       ║
# ║ You should have received a copy of the GNU General Public License     ║
# ║ along with this program.  If not, see <http://www.gnu.org/licenses/>. ║
# ╚-----------------------------------------------------------------------╝


# List of pane titles
running=($(tmux list-panes -F "#{pane_title}"))

# Variable to check for the presence of the desired application
iseditor=""

# Loop through all pane titles
for index in "${!running[@]}"; do
  # Check if the title contains the string "hx"
  if [[ "${running[$index]}" == *"hx"* ]]; then
    iseditor="1"
  fi
done

# Print result
if [ -z "$iseditor" ]; then
  echo 
else
  echo 1
fi



# BUG
# Return the index of the first (oldest) editor in the current window
# hxs=($(tmux list-panes -F '#{pane_current_command}'))
# for index in "${!hxs[@]}"; do
#   if [ "${hxs[$index]}" = "hx" ]; then
# 	echo $index
# 	exit
#   fi
# done

